# Generated by Django 4.2 on 2026-05-12 06:35

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nama_lengkap', models.CharField(max_length=255)),
                ('foto_profil', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], default='user', max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id_admin', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Berita',
            fields=[
                ('id_berita', models.AutoField(primary_key=True, serialize=False)),
                ('judul', models.CharField(max_length=255)),
                ('ringkasan', models.TextField(blank=True, null=True)),
                ('isi_lengkap', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('published', 'Published'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='draft', max_length=10)),
                ('gambar_url', models.ImageField(blank=True, null=True, upload_to='news/')),
                ('tanggal_publikasi', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feedback_admin', models.TextField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('view_count', models.IntegerField(default=0)),
                ('read_time', models.CharField(default='2 min read', max_length=50)),
                ('share_count', models.IntegerField(default=0)),
                ('id_admin', models.ForeignKey(blank=True, db_column='id_admin', null=True, on_delete=django.db.models.deletion.SET_NULL, to='berita.adminprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id_kategori', models.AutoField(primary_key=True, serialize=False)),
                ('nama_kategori', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(default='bi-tag', max_length=50)),
                ('urutan_tampil', models.IntegerField(default=1)),
                ('tgl_diperbarui', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['urutan_tampil', 'nama_kategori'],
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('tgl_daftar', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reaksi',
            fields=[
                ('id_reaksi', models.AutoField(primary_key=True, serialize=False)),
                ('tipe_reaksi', models.CharField(choices=[('wow', 'Wow'), ('idea', 'Idea'), ('thinking', 'Thinking'), ('sad', 'Sad'), ('down', 'Down'), ('love', 'Love')], max_length=10)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('berita', models.ForeignKey(db_column='id_berita', on_delete=django.db.models.deletion.CASCADE, related_name='reaksi_list', to='berita.berita')),
            ],
        ),
        migrations.CreateModel(
            name='Notifikasi',
            fields=[
                ('id_notifikasi', models.AutoField(primary_key=True, serialize=False)),
                ('tipe', models.CharField(max_length=50)),
                ('judul', models.CharField(max_length=255)),
                ('pesan', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('tgl_notifikasi', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifikasi', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LogAktivitas',
            fields=[
                ('id_log', models.AutoField(primary_key=True, serialize=False)),
                ('aksi', models.CharField(max_length=255)),
                ('waktu', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Komentar',
            fields=[
                ('id_komentar', models.AutoField(primary_key=True, serialize=False)),
                ('isi_komentar', models.TextField()),
                ('tgl_komentar', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('berita', models.ForeignKey(db_column='id_berita', on_delete=django.db.models.deletion.CASCADE, related_name='komentar_list', to='berita.berita')),
            ],
        ),
        migrations.AddField(
            model_name='berita',
            name='id_kategori',
            field=models.ForeignKey(db_column='id_kategori', on_delete=django.db.models.deletion.CASCADE, to='berita.kategori'),
        ),
        migrations.AddField(
            model_name='berita',
            name='id_user',
            field=models.ForeignKey(blank=True, db_column='id_user', null=True, on_delete=django.db.models.deletion.SET_NULL, to='berita.userprofile'),
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id_bookmark', models.AutoField(primary_key=True, serialize=False)),
                ('tgl_simpan', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
                ('berita', models.ForeignKey(db_column='id_berita', on_delete=django.db.models.deletion.CASCADE, to='berita.berita')),
            ],
            options={
                'unique_together': {('account', 'berita')},
            },
        ),
    ]
